// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTeacher(arg1:string):Promise<string>;

export function DeleteTeacher(arg1:string):Promise<string>;

export function ExportTeacher2Excel():Promise<string>;

export function GetTeacherList(arg1:string):Promise<string>;

export function UpdateTeacher(arg1:string):Promise<string>;
