// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTeacher(arg1) {
  return window['go']['service']['TeacherManager']['CreateTeacher'](arg1);
}

export function DeleteTeacher(arg1) {
  return window['go']['service']['TeacherManager']['DeleteTeacher'](arg1);
}

export function ExportTeacher2Excel() {
  return window['go']['service']['TeacherManager']['ExportTeacher2Excel']();
}

export function GetTeacherList(arg1) {
  return window['go']['service']['TeacherManager']['GetTeacherList'](arg1);
}

export function UpdateTeacher(arg1) {
  return window['go']['service']['TeacherManager']['UpdateTeacher'](arg1);
}
